services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_SOURCE=postgresql://postgres:password@db:5432/devdb?sslmode=disable

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
